### PR TITLE
chore: add top_p sampling example

### PR DESCRIPTION
**Pull request by mzbac**

### CODE REVIEW

**Comment by davidkoski** [comment]
It looks like the branch is based on an older version of the code and CI is failing, specifically this code is now removed (it is handled on the swift-transformers side):

- https://github.com/mzbac/mlx-swift-examples/blob/top_p/Libraries/LLM/Tokenizer.swift#L9

Can you rebase your branch on current main?

Thanks!

**Comment by mzbac** [comment]
@davidkoski I have rebased the master. Please let me know if there is anything else I need to change.

**Review by davidkoski — APPROVED** [review]
Thank you for the contribution!

Do you want to hook it up in the command line examples?

**Comment by mzbac** [comment]
> Thank you for the contribution!
> 
> Do you want to hook it up in the command line examples?

@davidkoski, do you have any preferences on this? I am thinking of creating a new command argument to specify the top P.

**Comment by davidkoski** [comment]
> > Thank you for the contribution!
> > Do you want to hook it up in the command line examples?
> 
> @davidkoski, do you have any preferences on this? I am thinking of creating a new command argument to specify the top P.

That sounds fine -- you can look at how temperature is hooked up.

**Pull request merged**
