### PR TITLE
Move models to subdirectory

### PR DESCRIPTION
**Pull request by DePasqualeOrg**
For better organization, and to better correspond to mlx-examples, I've moved the models to a subdirectory. This will also help me port future models, because I have some automated tooling to extract code from certain directories to use when prompting LLMs.

### CODE REVIEW

**Comment by davidkoski** [comment]
This probably needs a change in the .xcodeproj as well -- that has explicit references to the files/paths.

**Comment by DePasqualeOrg** [comment]
The project is using folders instead of groups, which has the advantage that the .xcodeproj file doesn't change when the file structure changes. There were no changes to that file after I built the package.

**Comment by davidkoski** [comment]
I think you are probably using the Package.swift to consume it -- this will work fine.  People who get the examples repo and try to build the example applications will fail.  This requires the .xcodeproj to be updated

**Comment by DePasqualeOrg** [comment]
Ah, thank you. That explains why I wasn't seeing the LLMEval target. What do you think about also converting to folders instead of groups? That would keep the .xcodeproj file cleaner when the file structure changes.

**Comment by davidkoski** [comment]
In the past I found that folders only worked for resources (e.g. files you want to copy into the output) and didn't work at all for source code.  It is worth a try (I haven't tried it in years) to see if it works now.

**Comment by DePasqualeOrg** [comment]
I've been using folders in all my projects for a little while now. Hopefully this will work now.

**Comment by DePasqualeOrg** [comment]
I'm not sure why the CI test is failing, because the targets build without any problems on my machine.

**Comment by davidkoski** [comment]
>         Reason: The project ‘mlx-swift-examples’ is damaged and cannot be opened. Examine the project file for invalid edits or unresolved source control conflicts.

It didn't look like conflicts to me, but maybe the version number that is in the file (the CI builder uses an older Xcode to make sure it still works on previous OSs)

**Comment by davidkoski** [comment]
This part in particular:

```
	objectVersion = 56;
	objectVersion = 71;
```

**Comment by DePasqualeOrg** [comment]
It looks like changing the version number doesn't work, so I reverted the conversion to folders.

**Pull request merged**
